// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tjwmfsfafrjsdwixutdd.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqd21mc2ZhZnJqc2R3aXh1dGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAxNDM5ODksImV4cCI6MjA0NTcxOTk4OX0.bQtuaK3kjHNC5pPppx4AOWa0YJ3E6Cfg1u8Bo3i9hgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);